f=open("test.txt","w")
f.write("my first file\n")
f.write("Ameera\n\n")
f.write("contains three lines\n")
f=open("test.txt",'r')
str=f.read()
print("read strings:",str)
f.close()
print("file",f.name,"closed")
